package win32

import "github.com/lxn/win"

var Sysmetrics = []struct {
	Index    int32
	Label    *uint16
	LabelLen int
	Desc     *uint16
	DescLen  int
}{
	{win.SM_CXSCREEN, Str("SM_CXSCREEN"), len("SM_CXSCREEN"), Str("Screen width in pixels"), len("Screen width in pixels")},
	{win.SM_CYSCREEN, Str("SM_CYSCREEN"), len("SM_CYSCREEN"), Str("Screen height in pixels"), len("Screen height in pixels")},
	{win.SM_CXVSCROLL, Str("SM_CXVSCROLL"), len("SM_CXVSCROLL"), Str("Vertical scroll width"), len("Vertical scroll width")},
	{win.SM_CYHSCROLL, Str("SM_CYHSCROLL"), len("SM_CYHSCROLL"), Str("Horizontal scroll height"), len("Horizontal scroll height")},
	{win.SM_CYCAPTION, Str("SM_CYCAPTION"), len("SM_CYCAPTION"), Str("Caption bar height"), len("Caption bar height")},
	{win.SM_CXBORDER, Str("SM_CXBORDER"), len("SM_CXBORDER"), Str("Window border width"), len("Window border width")},
	{win.SM_CYBORDER, Str("SM_CYBORDER"), len("SM_CYBORDER"), Str("Window border height"), len("Window border height")},
	{win.SM_CXFIXEDFRAME, Str("SM_CXFIXEDFRAME"), len("SM_CXFIXEDFRAME"), Str("Dialog window frame width"), len("Dialog window frame width")},
	{win.SM_CYFIXEDFRAME, Str("SM_CYFIXEDFRAME"), len("SM_CYFIXEDFRAME"), Str("Dialog window frame height"), len("Dialog window frame height")},
	{win.SM_CYVTHUMB, Str("SM_CYVTHUMB"), len("SM_CYVTHUMB"), Str("Vertical scroll thumb height"), len("Vertical scroll thumb height")},
	{win.SM_CXHTHUMB, Str("SM_CXHTHUMB"), len("SM_CXHTHUMB"), Str("Horizontal scroll thumb width"), len("Horizontal scroll thumb width")},
	{win.SM_CXICON, Str("SM_CXICON"), len("SM_CXICON"), Str("Icon width"), len("Icon width")},
	{win.SM_CYICON, Str("SM_CYICON"), len("SM_CYICON"), Str("Icon height"), len("Icon height")},
	{win.SM_CXCURSOR, Str("SM_CXCURSOR"), len("SM_CXCURSOR"), Str("Cursor width"), len("Cursor width")},
	{win.SM_CYCURSOR, Str("SM_CYCURSOR"), len("SM_CYCURSOR"), Str("Cursor height"), len("Cursor height")},
	{win.SM_CYMENU, Str("SM_CYMENU"), len("SM_CYMENU"), Str("Menu bar height"), len("Menu bar height")},
	{win.SM_CXFULLSCREEN, Str("SM_CXFULLSCREEN"), len("SM_CXFULLSCREEN"), Str("Full screen client area width"), len("Full screen client area width")},
	{win.SM_CYFULLSCREEN, Str("SM_CYFULLSCREEN"), len("SM_CYFULLSCREEN"), Str("Full screen client area height"), len("Full screen client area height")},
	{win.SM_CYKANJIWINDOW, Str("SM_CYKANJIWINDOW"), len("SM_CYKANJIWINDOW"), Str("Kanji window height"), len("Kanji window height")},
	{win.SM_MOUSEPRESENT, Str("SM_MOUSEPRESENT"), len("SM_MOUSEPRESENT"), Str("Mouse present flag"), len("Mouse present flag")},
	{win.SM_CYVSCROLL, Str("SM_CYVSCROLL"), len("SM_CYVSCROLL"), Str("Vertical scroll arrow height"), len("Vertical scroll arrow height")},
	{win.SM_CXHSCROLL, Str("SM_CXHSCROLL"), len("SM_CXHSCROLL"), Str("Horizontal scroll arrow width"), len("Horizontal scroll arrow width")},
	{win.SM_DEBUG, Str("SM_DEBUG"), len("SM_DEBUG"), Str("Debug version flag"), len("Debug version flag")},
	{win.SM_SWAPBUTTON, Str("SM_SWAPBUTTON"), len("SM_SWAPBUTTON"), Str("Mouse buttons swapped flag"), len("Mouse buttons swapped flag")},
	{win.SM_CXMIN, Str("SM_CXMIN"), len("SM_CXMIN"), Str("Minimum window width"), len("Minimum window width")},
	{win.SM_CYMIN, Str("SM_CYMIN"), len("SM_CYMIN"), Str("Minimum window height"), len("Minimum window height")},
	{win.SM_CXSIZE, Str("SM_CXSIZE"), len("SM_CXSIZE"), Str("Min/Max/Close button width"), len("Min/Max/Close button width")},
	{win.SM_CYSIZE, Str("SM_CYSIZE"), len("SM_CYSIZE"), Str("Min/Max/Close button height"), len("Min/Max/Close button height")},
	{win.SM_CXSIZEFRAME, Str("SM_CXSIZEFRAME"), len("SM_CXSIZEFRAME"), Str("Window sizing frame width"), len("Window sizing frame width")},
	{win.SM_CYSIZEFRAME, Str("SM_CYSIZEFRAME"), len("SM_CYSIZEFRAME"), Str("Window sizing frame height"), len("Window sizing frame height")},
	{win.SM_CXMINTRACK, Str("SM_CXMINTRACK"), len("SM_CXMINTRACK"), Str("Minimum window tracking width"), len("Minimum window tracking width")},
	{win.SM_CYMINTRACK, Str("SM_CYMINTRACK"), len("SM_CYMINTRACK"), Str("Minimum window tracking height"), len("Minimum window tracking height")},
	{win.SM_CXDOUBLECLK, Str("SM_CXDOUBLECLK"), len("SM_CXDOUBLECLK"), Str("Double click x tolerance"), len("Double click x tolerance")},
	{win.SM_CYDOUBLECLK, Str("SM_CYDOUBLECLK"), len("SM_CYDOUBLECLK"), Str("Double click y tolerance"), len("Double click y tolerance")},
	{win.SM_CXICONSPACING, Str("SM_CXICONSPACING"), len("SM_CXICONSPACING"), Str("Horizontal icon spacing"), len("Horizontal icon spacing")},
	{win.SM_CYICONSPACING, Str("SM_CYICONSPACING"), len("SM_CYICONSPACING"), Str("Vertical icon spacing"), len("Vertical icon spacing")},
	{win.SM_MENUDROPALIGNMENT, Str("SM_MENUDROPALIGNMENT"), len("SM_MENUDROPALIGNMENT"), Str("Left or right menu drop"), len("Left or right menu drop")},
	{win.SM_PENWINDOWS, Str("SM_PENWINDOWS"), len("SM_PENWINDOWS"), Str("Pen extensions installed"), len("Pen extensions installed")},
	{win.SM_DBCSENABLED, Str("SM_DBCSENABLED"), len("SM_DBCSENABLED"), Str("Double−Byte Char Set enabled"), len("Double−Byte Char Set enabled")},
	{win.SM_CMOUSEBUTTONS, Str("SM_CMOUSEBUTTONS"), len("SM_CMOUSEBUTTONS"), Str("Number of mouse buttons"), len("Number of mouse buttons")},
	{win.SM_SECURE, Str("SM_SECURE"), len("SM_SECURE"), Str("Security present flag"), len("Security present flag")},
	{win.SM_CXEDGE, Str("SM_CXEDGE"), len("SM_CXEDGE"), Str("3−D border width"), len("3−D border width")},
	{win.SM_CYEDGE, Str("SM_CYEDGE"), len("SM_CYEDGE"), Str("3−D border height"), len("3−D border height")},
	{win.SM_CXMINSPACING, Str("SM_CXMINSPACING"), len("SM_CXMINSPACING"), Str("Minimized window spacing width"), len("Minimized window spacing width")},
	{win.SM_CYMINSPACING, Str("SM_CYMINSPACING"), len("SM_CYMINSPACING"), Str("Minimized window spacing height"), len("Minimized window spacing height")},
	{win.SM_CXSMICON, Str("SM_CXSMICON"), len("SM_CXSMICON"), Str("Small icon width"), len("Small icon width")},
	{win.SM_CYSMICON, Str("SM_CYSMICON"), len("SM_CYSMICON"), Str("Small icon height"), len("Small icon height")},
	{win.SM_CYSMCAPTION, Str("SM_CYSMCAPTION"), len("SM_CYSMCAPTION"), Str("Small caption height"), len("Small caption height")},
	{win.SM_CXSMSIZE, Str("SM_CXSMSIZE"), len("SM_CXSMSIZE"), Str("Small caption button width"), len("Small caption button width")},
	{win.SM_CYSMSIZE, Str("SM_CYSMSIZE"), len("SM_CYSMSIZE"), Str("Small caption button height"), len("Small caption button height")},
	{win.SM_CXMENUSIZE, Str("SM_CXMENUSIZE"), len("SM_CXMENUSIZE"), Str("Menu bar button width"), len("Menu bar button width")},
	{win.SM_CYMENUSIZE, Str("SM_CYMENUSIZE"), len("SM_CYMENUSIZE"), Str("Menu bar button height"), len("Menu bar button height")},
	{win.SM_ARRANGE, Str("SM_ARRANGE"), len("SM_ARRANGE"), Str("How minimized windows arranged"), len("How minimized windows arranged")},
	{win.SM_CXMINIMIZED, Str("SM_CXMINIMIZED"), len("SM_CXMINIMIZED"), Str("Minimized window width"), len("Minimized window width")},
	{win.SM_CYMINIMIZED, Str("SM_CYMINIMIZED"), len("SM_CYMINIMIZED"), Str("Minimized window height"), len("Minimized window height")},
	{win.SM_CXMAXTRACK, Str("SM_CXMAXTRACK"), len("SM_CXMAXTRACK"), Str("Maximum draggable width"), len("Maximum draggable width")},
	{win.SM_CYMAXTRACK, Str("SM_CYMAXTRACK"), len("SM_CYMAXTRACK"), Str("Maximum draggable height"), len("Maximum draggable height")},
	{win.SM_CXMAXIMIZED, Str("SM_CXMAXIMIZED"), len("SM_CXMAXIMIZED"), Str("Width of maximized window"), len("Width of maximized window")},
	{win.SM_CYMAXIMIZED, Str("SM_CYMAXIMIZED"), len("SM_CYMAXIMIZED"), Str("Height of maximized window"), len("Height of maximized window")},
	{win.SM_NETWORK, Str("SM_NETWORK"), len("SM_NETWORK"), Str("Network present flag"), len("Network present flag")},
	{win.SM_CLEANBOOT, Str("SM_CLEANBOOT"), len("SM_CLEANBOOT"), Str("How system was booted"), len("How system was booted")},
	{win.SM_CXDRAG, Str("SM_CXDRAG"), len("SM_CXDRAG"), Str("Avoid drag x tolerance"), len("Avoid drag x tolerance")},
	{win.SM_CYDRAG, Str("SM_CYDRAG"), len("SM_CYDRAG"), Str("Avoid drag y tolerance"), len("Avoid drag y tolerance")},
	{win.SM_SHOWSOUNDS, Str("SM_SHOWSOUNDS"), len("SM_SHOWSOUNDS"), Str("Present sounds visually"), len("Present sounds visually")},
	{win.SM_CXMENUCHECK, Str("SM_CXMENUCHECK"), len("SM_CXMENUCHECK"), Str("Menu check−mark width"), len("Menu check−mark width")},
	{win.SM_CYMENUCHECK, Str("SM_CYMENUCHECK"), len("SM_CYMENUCHECK"), Str("Menu check−mark height"), len("Menu check−mark height")},
	{win.SM_SLOWMACHINE, Str("SM_SLOWMACHINE"), len("SM_SLOWMACHINE"), Str("Slow processor flag"), len("Slow processor flag")},
	{win.SM_MIDEASTENABLED, Str("SM_MIDEASTENABLED"), len("SM_MIDEASTENABLED"), Str("Hebrew and Arabic enabled flag"), len("Hebrew and Arabic enabled flag")},
	{win.SM_MOUSEWHEELPRESENT, Str("SM_MOUSEWHEELPRESENT"), len("SM_MOUSEWHEELPRESENT"), Str("Mouse wheel present flag"), len("Mouse wheel present flag")},
	{win.SM_XVIRTUALSCREEN, Str("SM_XVIRTUALSCREEN"), len("SM_XVIRTUALSCREEN"), Str("Virtual screen x origin"), len("Virtual screen x origin")},
	{win.SM_YVIRTUALSCREEN, Str("SM_YVIRTUALSCREEN"), len("SM_YVIRTUALSCREEN"), Str("Virtual screen y origin"), len("Virtual screen y origin")},
	{win.SM_CXVIRTUALSCREEN, Str("SM_CXVIRTUALSCREEN"), len("SM_CXVIRTUALSCREEN"), Str("Virtual screen width"), len("Virtual screen width")},
	{win.SM_CYVIRTUALSCREEN, Str("SM_CYVIRTUALSCREEN"), len("SM_CYVIRTUALSCREEN"), Str("Virtual screen height"), len("Virtual screen height")},
	{win.SM_CMONITORS, Str("SM_CMONITORS"), len("SM_CMONITORS"), Str("Number of monitors"), len("Number of monitors")},
	{win.SM_SAMEDISPLAYFORMAT, Str("SM_SAMEDISPLAYFORMAT"), len("SM_SAMEDISPLAYFORMAT"), Str("Same color format flag"), len("Same color format flag")},
}
