// Code generated by 'go generate'; DO NOT EDIT.

package win32

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	moduser32 = windows.NewLazySystemDLL("user32.dll")
	modwinmm  = windows.NewLazySystemDLL("winmm.dll")

	procGetSystemMetrics = moduser32.NewProc("GetSystemMetrics")
	procMessageBoxW      = moduser32.NewProc("MessageBoxW")
	procPlaySoundW       = modwinmm.NewProc("PlaySoundW")
)

func GetSystemMetrics(nIndex int) (ret int, err error) {
	r0, _, e1 := syscall.Syscall(procGetSystemMetrics.Addr(), 1, uintptr(nIndex), 0, 0)
	ret = int(r0)
	if ret == 0 {
		err = errnoErr(e1)
	}
	return
}

func MessageBox(hwnd HWND, text string, caption string, boxtype uint32) (ret int32, err error) {
	var _p0 *uint16
	_p0, err = syscall.UTF16PtrFromString(text)
	if err != nil {
		return
	}
	var _p1 *uint16
	_p1, err = syscall.UTF16PtrFromString(caption)
	if err != nil {
		return
	}
	return _MessageBox(hwnd, _p0, _p1, boxtype)
}

func _MessageBox(hwnd HWND, text *uint16, caption *uint16, boxtype uint32) (ret int32, err error) {
	r0, _, e1 := syscall.Syscall6(procMessageBoxW.Addr(), 4, uintptr(hwnd), uintptr(unsafe.Pointer(text)), uintptr(unsafe.Pointer(caption)), uintptr(boxtype), 0, 0)
	ret = int32(r0)
	if ret == 0 {
		err = errnoErr(e1)
	}
	return
}

func PlaySound(sound string, hmod uintptr, flags uint32) (ret bool, err error) {
	var _p0 *uint16
	_p0, err = syscall.UTF16PtrFromString(sound)
	if err != nil {
		return
	}
	return _PlaySound(_p0, hmod, flags)
}

func _PlaySound(sound *uint16, hmod uintptr, flags uint32) (ret bool, err error) {
	r0, _, e1 := syscall.Syscall(procPlaySoundW.Addr(), 3, uintptr(unsafe.Pointer(sound)), uintptr(hmod), uintptr(flags))
	ret = r0 != 0
	if ret == false {
		err = errnoErr(e1)
	}
	return
}
