package sysmets

import "x/win32"

var Sysmetrics = [...]struct {
	Index int32
	Label string
	Desc  string
}{
	{win32.SM_CXSCREEN, "SM_CXSCREEN", "Screen width in pixels:"},
	{win32.SM_CYSCREEN, "SM_CYSCREEN", "Screen height in pixels:"},
	{win32.SM_CXVSCROLL, "SM_CXVSCROLL", "Vertical scroll width:"},
	{win32.SM_CYHSCROLL, "SM_CYHSCROLL", "Horizontal scroll height:"},
	{win32.SM_CYCAPTION, "SM_CYCAPTION", "Caption bar height:"},
	{win32.SM_CXBORDER, "SM_CXBORDER", "Window border width:"},
	{win32.SM_CYBORDER, "SM_CYBORDER", "Window border height:"},
	{win32.SM_CXFIXEDFRAME, "SM_CXFIXEDFRAME", "Dialog window frame width:"},
	{win32.SM_CYFIXEDFRAME, "SM_CYFIXEDFRAME", "Dialog window frame height:"},
	{win32.SM_CYVTHUMB, "SM_CYVTHUMB", "Vertical scroll thumb height:"},
	{win32.SM_CXHTHUMB, "SM_CXHTHUMB", "Horizontal scroll thumb width:"},
	{win32.SM_CXICON, "SM_CXICON", "Icon width:"},
	{win32.SM_CYICON, "SM_CYICON", "Icon height:"},
	{win32.SM_CXCURSOR, "SM_CXCURSOR", "Cursor width:"},
	{win32.SM_CYCURSOR, "SM_CYCURSOR", "Cursor height:"},
	{win32.SM_CYMENU, "SM_CYMENU", "Menu bar height:"},
	{win32.SM_CXFULLSCREEN, "SM_CXFULLSCREEN", "Full screen client area width:"},
	{win32.SM_CYFULLSCREEN, "SM_CYFULLSCREEN", "Full screen client area height:"},
	{win32.SM_CYKANJIWINDOW, "SM_CYKANJIWINDOW", "Kanji window height:"},
	{win32.SM_MOUSEPRESENT, "SM_MOUSEPRESENT", "Mouse present flag:"},
	{win32.SM_CYVSCROLL, "SM_CYVSCROLL", "Vertical scroll arrow height:"},
	{win32.SM_CXHSCROLL, "SM_CXHSCROLL", "Horizontal scroll arrow width:"},
	{win32.SM_DEBUG, "SM_DEBUG", "Debug version flag:"},
	{win32.SM_SWAPBUTTON, "SM_SWAPBUTTON", "Mouse buttons swapped flag:"},
	{win32.SM_CXMIN, "SM_CXMIN", "Minimum window width:"},
	{win32.SM_CYMIN, "SM_CYMIN", "Minimum window height:"},
	{win32.SM_CXSIZE, "SM_CXSIZE", "Min/Max/Close button width:"},
	{win32.SM_CYSIZE, "SM_CYSIZE", "Min/Max/Close button height:"},
	{win32.SM_CXSIZEFRAME, "SM_CXSIZEFRAME", "Window sizing frame width:"},
	{win32.SM_CYSIZEFRAME, "SM_CYSIZEFRAME", "Window sizing frame height:"},
	{win32.SM_CXMINTRACK, "SM_CXMINTRACK", "Minimum window tracking width:"},
	{win32.SM_CYMINTRACK, "SM_CYMINTRACK", "Minimum window tracking height:"},
	{win32.SM_CXDOUBLECLK, "SM_CXDOUBLECLK", "Double click x tolerance:"},
	{win32.SM_CYDOUBLECLK, "SM_CYDOUBLECLK", "Double click y tolerance:"},
	{win32.SM_CXICONSPACING, "SM_CXICONSPACING", "Horizontal icon spacing:"},
	{win32.SM_CYICONSPACING, "SM_CYICONSPACING", "Vertical icon spacing:"},
	{win32.SM_MENUDROPALIGNMENT, "SM_MENUDROPALIGNMENT", "Left or right menu drop:"},
	{win32.SM_PENWINDOWS, "SM_PENWINDOWS", "Pen extensions installed:"},
	{win32.SM_DBCSENABLED, "SM_DBCSENABLED", "Double-Byte Char Set enabled:"},
	{win32.SM_CMOUSEBUTTONS, "SM_CMOUSEBUTTONS", "Number of mouse buttons:"},
	{win32.SM_SECURE, "SM_SECURE", "Security present flag:"},
	{win32.SM_CXEDGE, "SM_CXEDGE", "3-D border width:"},
	{win32.SM_CYEDGE, "SM_CYEDGE", "3-D border height:"},
	{win32.SM_CXMINSPACING, "SM_CXMINSPACING", "Minimized window spacing width:"},
	{win32.SM_CYMINSPACING, "SM_CYMINSPACING", "Minimized window spacing height:"},
	{win32.SM_CXSMICON, "SM_CXSMICON", "Small icon width:"},
	{win32.SM_CYSMICON, "SM_CYSMICON", "Small icon height:"},
	{win32.SM_CYSMCAPTION, "SM_CYSMCAPTION", "Small caption height:"},
	{win32.SM_CXSMSIZE, "SM_CXSMSIZE", "Small caption button width:"},
	{win32.SM_CYSMSIZE, "SM_CYSMSIZE", "Small caption button height:"},
	{win32.SM_CXMENUSIZE, "SM_CXMENUSIZE", "Menu bar button width:"},
	{win32.SM_CYMENUSIZE, "SM_CYMENUSIZE", "Menu bar button height:"},
	{win32.SM_ARRANGE, "SM_ARRANGE", "How minimized windows arranged:"},
	{win32.SM_CXMINIMIZED, "SM_CXMINIMIZED", "Minimized window width:"},
	{win32.SM_CYMINIMIZED, "SM_CYMINIMIZED", "Minimized window height:"},
	{win32.SM_CXMAXTRACK, "SM_CXMAXTRACK", "Maximum draggable width:"},
	{win32.SM_CYMAXTRACK, "SM_CYMAXTRACK", "Maximum draggable height:"},
	{win32.SM_CXMAXIMIZED, "SM_CXMAXIMIZED", "Width of maximized window:"},
	{win32.SM_CYMAXIMIZED, "SM_CYMAXIMIZED", "Height of maximized window:"},
	{win32.SM_NETWORK, "SM_NETWORK", "Network present flag:"},
	{win32.SM_CLEANBOOT, "SM_CLEANBOOT", "How system was booted:"},
	{win32.SM_CXDRAG, "SM_CXDRAG", "Avoid drag x tolerance:"},
	{win32.SM_CYDRAG, "SM_CYDRAG", "Avoid drag y tolerance:"},
	{win32.SM_SHOWSOUNDS, "SM_SHOWSOUNDS", "Present sounds visually:"},
	{win32.SM_CXMENUCHECK, "SM_CXMENUCHECK", "Menu check-mark width:"},
	{win32.SM_CYMENUCHECK, "SM_CYMENUCHECK", "Menu check-mark height:"},
	{win32.SM_SLOWMACHINE, "SM_SLOWMACHINE", "Slow processor flag:"},
	{win32.SM_MIDEASTENABLED, "SM_MIDEASTENABLED", "Hebrew and Arabic enabled flag:"},
	{win32.SM_MOUSEWHEELPRESENT, "SM_MOUSEWHEELPRESENT", "Mouse wheel present flag:"},
	{win32.SM_XVIRTUALSCREEN, "SM_XVIRTUALSCREEN", "Virtual screen x origin:"},
	{win32.SM_YVIRTUALSCREEN, "SM_YVIRTUALSCREEN", "Virtual screen y origin:"},
	{win32.SM_CXVIRTUALSCREEN, "SM_CXVIRTUALSCREEN", "Virtual screen width:"},
	{win32.SM_CYVIRTUALSCREEN, "SM_CYVIRTUALSCREEN", "Virtual screen height:"},
	{win32.SM_CMONITORS, "SM_CMONITORS", "Number of monitors:"},
	{win32.SM_SAMEDISPLAYFORMAT, "SM_SAMEDISPLAYFORMAT", "Same color format flag:"},
}

const NUMLINES = len(Sysmetrics)
